packages:
  - 'packages/*'
  - 'packages/mcp-servers/*'
  - 'apps/*'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - 'bcrypt'
  - 'esbuild'
  - 'msgpackr-extract'
  - 'prisma'
